service: desafio
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: david
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            Fn::GetAtt:
              - Transaction
              - Arn

constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
  getAll:
    handler: index.getAll
    events:
      - httpApi:
          method: get
          path: /transaction

resources:
  Resources:
    Transaction:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Transaction
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-lift
